services:
  # 1. Servicio de la Aplicación (Laravel PHP)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: massha-app
    container_name: massha-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - massha-network

  # 2. Servicio de Servidor Web (Nginx)
  nginx:
    image: nginx:alpine
    container_name: massha-nginx
    restart: unless-stopped
    ports:
      - "8080:80"  # Usaremos el puerto 8080 en tu PC para no chocar con XAMPP (que suele usar el 80)
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - massha-network
    depends_on:
      - app

  # 3. Servicio de Base de Datos (MySQL)
  db:
    image: mysql:8.0
    container_name: massha-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306" # Usaremos el puerto 3307 para no chocar con el MySQL de XAMPP (3306)
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - massha-network

  # 4. Servicio de Calidad de Código (SonarQube) - ISO 25000
  sonarqube:
    image: sonarqube:community
    container_name: massha-sonar
    restart: unless-stopped
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
    networks:
      - massha-network
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs

  # 5. Escáner de Sonar (Ejecuta el análisis)
  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: massha-scanner
    profiles: ["scan"] # Solo se ejecuta cuando lo pedimos explícitamente
    depends_on:
      - sonarqube
    networks:
      - massha-network
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_TOKEN=sqa_5cd9826b856efe9d5660cc4b91bc2f8f2a36f18a
    volumes:
      - ./:/usr/src

# Definición de redes y volúmenes
networks:
  massha-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  sonar_data:
    driver: local
  sonar_logs:
    driver: local
  sonar_extensions:
    driver: local